insert into ramo_atividade (descricao) values ('Distribuição de alimentos');
insert into ramo_atividade (descricao) values ('Telecomunicações');
insert into ramo_atividade (descricao) values ('Vestuário');
insert into ramo_atividade (descricao) values ('Lavanderia');
insert into ramo_atividade (descricao) values ('Gráfica');
insert into ramo_atividade (descricao) values ('Mecânica');
insert into ramo_atividade (descricao) values ('Turismo');
insert into ramo_atividade (descricao) values ('Saúde');
insert into ramo_atividade (descricao) values ('Educação');
insert into ramo_atividade (descricao) values ('Lazer');

insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '70.311.193/0001-87', 'Mercado do João', 'João Mercado e Distribuidor de Alimentos Ltda', 'LTDA', '2009-03-02', 1);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '52.822.994/0001-25', 'Fale Mais', 'Fale Mais Telecom S.A.', 'SA', '1997-12-10', 2);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '41.952.519/0001-57', 'Maria de Souza da Silva', 'Maria de Souza da Silva', 'MEI', '2014-10-15', 3);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '25.333.444/0001-11', 'Auto Peças Progresso', 'Auto Peças Progresso Ltda', 'LTDA', '2010-06-18', 6);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '11.998.224/0001-99', 'Tourist Trip', 'Tourist Trip Viagens e Turismo Ltda', 'LTDA', '2015-04-12', 7);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '22.776.399/0001-55', 'Clínica Saúde Viva', 'Saúde Viva Serviços Médicos Ltda', 'LTDA', '2007-08-01', 8);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '32.124.889/0001-77', 'Educa Tech', 'Educa Tech Soluções Educacionais S.A.', 'SA', '2003-11-20', 9);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '49.222.114/0001-33', 'Lazer Total', 'Lazer Total Entretenimento Ltda', 'LTDA', '2011-05-10', 10);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '16.134.777/0001-45', 'Fábrica de Roupas ABC', 'Fábrica de Roupas ABC Ltda', 'LTDA', '2012-09-17', 3);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '12.523.777/0001-88', 'Gráfica Expressa', 'Gráfica Expressa S.A.', 'SA', '2008-12-03', 5);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '15.856.678/0001-33', 'Alimentos Frescos', 'Distribuidora de Alimentos Frescos Ltda', 'LTDA', '2016-07-21', 1);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '45.667.122/0001-44', 'Fale Conosco Telecom', 'Fale Conosco Telecomunicações S.A.', 'SA', '1999-01-15', 2);
insert into empresa ( cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ( '21.658.234/0001-66', 'Serviços Lavanderia Limpa', 'Serviços Lavanderia Limpa Ltda', 'LTDA', '2014-02-25', 4);
